import { createRequestHandler } from "react-router";
// @ts-ignore: generated by `pnpm build` before `wrangler deploy`.
import * as build from "../build/server/index.js";

export default {
  async fetch(request, env, ctx) {
    const handler = createRequestHandler(build, "production");

    return handler(request, {
      cloudflare: { env, ctx },
    });
  },
} satisfies ExportedHandler<Env>;
